[package]
org = "hasitha"
name = "ballerina"
version = "0.1.0"
distribution = "2201.9.0"

[build-options]
observabilityIncluded = true

[[platform.java17.dependency]]
groupId = "io.ballerina.lib"
artifactId = "native"
version = "0.1.0"
path = "../native/build/libs/native-0.1.0.jar"

[[platform.java17.dependency]]
path = "./lib/ballerina-lang-2201.9.0.jar"
groupId = "org.ballerinalang"
artifactId = "ballerina-lang"
version = "2201.9.0"

[[platform.java17.dependency]]
groupId = "org.ballerinalang"
artifactId = "ballerina-tools-api"
version = "2201.9.0"
path = "./lib/ballerina-tools-api-2201.9.0.jar"

[[platform.java17.dependency]]
groupId = "com.google.code.gson"
artifactId = "gson"
version = "2.8.8"
path="./lib/gson-2.8.8.jar"

[[platform.java17.dependency]]
groupId="com.github.zafarkhaja"
artifactId="java-semver"
version="0.9.0"
path="./lib/java-semver-0.9.0.jar"

[[platform.java17.dependency]]
path = "./lib/central-client-2201.9.0.jar"
groupId = "org.ballerinalang"
artifactId = "central-client"
version = "2.4.7"

[[platform.java17.dependency]]
groupId = "org.apache.commons"
artifactId = "commons-compress"
version = "1.21"
path = "./lib/commons-compress-1.21.jar"

[[platform.java17.dependency]]
groupId = "com.squareup.okhttp3"
artifactId = "okhttp"
version = "4.9.3"
path = "./lib/okhttp-3.14.0.jar"

[[platform.java17.dependency]]
groupId = "com.squareup.okio"
artifactId = "okio"
version = "2.10.0"
path = "./lib/okio-jvm-3.4.0.jar"

[[platform.java17.dependency]]
groupId = "commons-io"
artifactId="commons-io"
version="2.12.0"
path="./lib/commons-io-2.12.0.jar"

[[platform.java17.dependency]]
groupId = "org.ballerinalang"
artifactId = "ballerina-parser"
version = "2201.9.0"
path = "./lib/ballerina-parser-2201.9.0.jar"